### ISSUE TITLE
RuntimeWarning: covariance is not positive-semidefinite.

### ISSUE THREAD

**Issue by leesaudan2** [kevingroup/techniXnippets#2]
Code fragments in [intro_to_jupyter_notebook.ipynb](https://github.com/kevingroup/techniXnippets/blob/master/intro_to_jupyter_notebook.ipynb) give the warning:
`RuntimeWarning: covariance is not positive-semidefinite.`

These could be avoided if the covariance matrix is symmetric.

**Comment by fuxialexander** [comment]
Done in https://github.com/kevingroup/techniXnippets/commit/d2897badc4f06024112150224705efb8281fb8db
